### PR TITLE
Several enhancements

### PR DESCRIPTION
**Pull request by BlackCatDeployment**
image

### CODE REVIEW

**Comment by BlackCatDeployment** [comment]
I finished the Site Roles enhancement yuuhhh! It was a pain :)
Have a nice review!

**Comment by BlackCatDeployment** [comment]
image

**Comment by BlackCatDeployment** [comment]
Add Paul's PR.

**Comment by ChadSimmons** [comment]
GREAT additions.  I was about to start writing the Site Maintenance Tasks update... now I don't have to!

**Comment by BlackCatDeployment** [comment]
Thks @ChadSimmons  :)

**Pull request merged**
