### PR TITLE
DocumentCMCB.ps1: Collections enum improvements + some bugfixes

### PR DESCRIPTION
**Pull request by BlackCatDeployment**
- Fix enum Membership Rules (query, include, direct)
- Improve HTML display report for device collection enum
- Add Exclude membership rule enum

### CODE REVIEW

**Comment by BlackCatDeployment** [comment]
First of all, thanks for your work!
I fixed issue with enumerating device collection membership rules.
Glad to help you for this wonderful tool! :)

**Comment by BlackCatDeployment** [comment]
Added folder's device collection.

**Comment by BlackCatDeployment** [comment]
Improved User Collections enum.

**Comment by BlackCatDeployment** [comment]
Added fix on Get-WMIObject calls when SMSProvider parameter is missing.

**Comment by paulwetter** [comment]
I like these additions, especially collection folders.  Just running them against my environment but looks good so far.  Thanks!

**Pull request merged**
