### PR TITLE
Added Write-ProgressEx

### PR DESCRIPTION
**Pull request by ChadSimmons**
Added function to output with Write-Progress, Write-Verbose, and Write-CMLog in a single command.  Added example function calls through line 1009; obviously more would need to be added if the proposed change is adopted.

### CODE REVIEW

**Comment by paulwetter** [comment]
Hey Chad.  Looking at your additional function.  Trying to better understand what is being accomplished with the function beyond prettier output.  Perhaps a user story where this is a benefit.  Not opposed to it just trying to figure out the origin.
Thanks.

**Comment by ChadSimmons** [comment]
You are correct, the function is just for more standardized output/logging/feedback mainly for interactive execution.  Since the script runs for ~30 minutes (give or take depending on the environment), I found it useful to know what it was doing at a few points along the way.
So, it's just a minor suggestion... no sweat if it isn't merged in.  The script is awesome as is.

**Comment by paulwetter** [comment]
The more I think about it the more I like it.  However, some of the verbose logging may have to be moved over to debug logging or something for extended troubleshooting.  Which would make more sense anyways...

**Comment by ChadSimmons** [comment]
Thanks Paul.  If you would like me to put some more effort into the messaging conversion I'd be happy to.

**Comment by paulwetter** [comment]
If you have the will, go for it!  I'm not going to have time to do too much in the next several weeks.  If anything, I'll be adding stuff for the pending 1806 release.  But, I'd be happy for the additional input to make this thing more user friendly.

**Comment by ChadSimmons** [comment]
Thanks.  I'll make some additions over the new few weeks as I stand up a new environment for a customer.

**Comment by ChadSimmons** [comment]
This will resolve Issue #26 when complete.

**Pull request merged**
